### ISSUE TITLE
`autogen.sh` fails

### ISSUE THREAD

**Issue by lemzwerg** [pete4abw/libtrash#5]
Running `autogen.sh` of the head of the 'autotools' branch (commit 6a7d8d48eecd334b58d6277b9426a9f62864f063) fails: the macro `AC_DISABLE_STATIC` is not defined.  AFAICS, such a macro is part of 'libtool', which is not used at all for configuration in this branch.

**Comment by lemzwerg** [comment]
Please ignore this report; it was a misconfiguration on my side. 

Explanation: I have versions of 'autoconf' and 'automake' installed in `/usr/local/` but not 'libtool'; this doesn't work out of the box with `autoreconf` – either install 'libtool' also in `/usr/local` (which I've done now) or add appropriate options and/or environment variables.

**Comment by pete4abw** [comment]
> Please ignore this report; it was a misconfiguration on my side.
> 
With system tools, I have found it best to use them as packaged and installed by your distro. Having alternate versions in `/usr/local` or `$HOME/bin` will usually lead to some pain!

> Explanation: I have versions of 'autoconf' and 'automake' installed in `/usr/local/` but not 'libtool'; this doesn't work out of the box with `autoreconf` – either install 'libtool' also in `/usr/local` (which I've done now) or add appropriate options and/or environment variables.

Thank you for your report anyway. I am glad it worked out for you.
